# Phase 4 : Feature Selection using mRMR

## Objectives

- Load cleaned dataset
- Encode target labels
- Apply mRMR
- Select Top Features
- Save selected dataset

In [8]:
# ============================================================
# Import Libraries
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries Imported")

Libraries Imported

In [9]:
PROJECT_DIR = Path(r"A:\Network-Intrusion-Detection-System")

DATASET_PATH = PROJECT_DIR/"dataset"/"cleaned"/"cleaned_cicids2017.csv"

df = pd.read_csv(DATASET_PATH)

print(df.shape)

(2522362, 79)

In [10]:
X = df.drop(columns=["Label"])

y = df["Label"]

print(X.shape)

print(y.shape)

(2522362, 78)
(2522362,)

In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y_encoded = encoder.fit_transform(y)

print("Classes")

print(encoder.classes_)

Classes
['BENIGN' 'Bot' 'DDoS' 'DoS GoldenEye' 'DoS Hulk' 'DoS Slowhttptest'
 'DoS slowloris' 'FTP-Patator' 'Heartbleed' 'Infiltration' 'PortScan'
 'SSH-Patator' 'Web Attack � Brute Force' 'Web Attack � Sql Injection'
 'Web Attack � XSS']

In [12]:
!pip install mrmr-selection

Requirement already satisfied: mrmr-selection in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (0.2.8)
Requirement already satisfied: category-encoders in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (2.9.0)
Requirement already satisfied: jinja2 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (3.1.4)
Requirement already satisfied: tqdm in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (4.66.5)
Requirement already satisfied: joblib in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (1.4.2)
Requirement already satisfied: pandas>=1.0.3 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (2.1.4)
Requirement already satisfied: numpy>=1.18.1 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (1.26.4)
Requirement already satisfied: scikit-learn in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (1.6.1)
Requirement already satisfied: scipy in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (1.16.2)
Requirement already satisfied: polars>=0.12.5 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from mrmr-selection) (1.42.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.3->mrmr-selection) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.3->mrmr-selection) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.3->mrmr-selection) (2024.1)
Requirement already satisfied: polars-runtime-32==1.42.1 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from polars>=0.12.5->mrmr-selection) (1.42.1)
Requirement already satisfied: six>=1.5 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.3->mrmr-selection) (1.16.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from category-encoders->mrmr-selection) (1.0.2)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from category-encoders->mrmr-selection) (0.14.6)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn->mrmr-selection) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from statsmodels>=0.9.0->category-encoders->mrmr-selection) (24.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from jinja2->mrmr-selection) (2.1.5)
Requirement already satisfied: colorama in c:\users\sabar\appdata\local\programs\python\python312\lib\site-packages (from tqdm->mrmr-selection) (0.4.6)

WARNING: Ignoring invalid distribution ~orch (C:\Users\sabar\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sabar\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sabar\AppData\Local\Programs\Python\Python312\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from mrmr import mrmr_classif

In [15]:
selected_features = mrmr_classif(
    X=X,
    y=pd.Series(y_encoded),
    K=30
)

KeyboardInterrupt:

In [16]:
print(selected_features)

['Fwd IAT Std', 'Bwd IAT Min', 'Flow IAT Min', 'Bwd Packet Length Std', 'Bwd Packet Length Mean', 'Avg Bwd Segment Size', 'Idle Min', 'Bwd Packet Length Max', 'Idle Mean', 'Packet Length Std', 'Idle Max', 'Flow IAT Max', 'Max Packet Length', 'Fwd IAT Max', 'Packet Length Variance', 'Average Packet Size', 'Packet Length Mean', 'Active Min', 'FIN Flag Count', 'Active Std', 'Flow IAT Std', 'PSH Flag Count', 'Active Mean', 'Fwd IAT Total', 'ACK Flag Count', 'Flow Duration', 'Bwd IAT Std', 'Subflow Fwd Bytes', 'Flow IAT Mean', 'Min Packet Length']

In [17]:
selected_df = X[selected_features]

selected_df["Label"] = y.values

selected_df.head()

,Fwd IAT Std,Bwd IAT Min,Flow IAT Min,Bwd Packet Length Std,Bwd Packet Length Mean,Avg Bwd Segment Size,Idle Min,Bwd Packet Length Max,Idle Mean,Packet Length Std,...,PSH Flag Count,Active Mean,Fwd IAT Total,ACK Flag Count,Flow Duration,Bwd IAT Std,Subflow Fwd Bytes,Flow IAT Mean,Min Packet Length,Label
0,0.0,0,3,0.0,0.0,0.0,0,0,0.0,0.0,...,0,0.0,3,1,3,0.0,12,3.0,6,BENIGN
1,0.0,0,109,0.0,6.0,6.0,0,6,0.0,0.0,...,0,0.0,0,1,109,0.0,6,109.0,6,BENIGN
2,0.0,0,52,0.0,6.0,6.0,0,6,0.0,0.0,...,0,0.0,0,1,52,0.0,6,52.0,6,BENIGN
3,0.0,0,34,0.0,6.0,6.0,0,6,0.0,0.0,...,0,0.0,0,1,34,0.0,6,34.0,6,BENIGN
4,0.0,0,3,0.0,0.0,0.0,0,0,0.0,0.0,...,0,0.0,3,1,3,0.0,12,3.0,6,BENIGN

In [18]:
OUTPUT_PATH = PROJECT_DIR/"dataset"/"cleaned"/"selected_features.csv"

selected_df.to_csv(OUTPUT_PATH,index=False)

print("Saved Successfully")

print(OUTPUT_PATH)

Saved Successfully
A:\Network-Intrusion-Detection-System\dataset\cleaned\selected_features.csv

In [19]:
selected_df.head()

,Fwd IAT Std,Bwd IAT Min,Flow IAT Min,Bwd Packet Length Std,Bwd Packet Length Mean,Avg Bwd Segment Size,Idle Min,Bwd Packet Length Max,Idle Mean,Packet Length Std,...,PSH Flag Count,Active Mean,Fwd IAT Total,ACK Flag Count,Flow Duration,Bwd IAT Std,Subflow Fwd Bytes,Flow IAT Mean,Min Packet Length,Label
0,0.0,0,3,0.0,0.0,0.0,0,0,0.0,0.0,...,0,0.0,3,1,3,0.0,12,3.0,6,BENIGN
1,0.0,0,109,0.0,6.0,6.0,0,6,0.0,0.0,...,0,0.0,0,1,109,0.0,6,109.0,6,BENIGN
2,0.0,0,52,0.0,6.0,6.0,0,6,0.0,0.0,...,0,0.0,0,1,52,0.0,6,52.0,6,BENIGN
3,0.0,0,34,0.0,6.0,6.0,0,6,0.0,0.0,...,0,0.0,0,1,34,0.0,6,34.0,6,BENIGN
4,0.0,0,3,0.0,0.0,0.0,0,0,0.0,0.0,...,0,0.0,3,1,3,0.0,12,3.0,6,BENIGN

In [20]:
selected_df.shape

(2522362, 31)

In [21]:
selected_df.columns

Index(['Fwd IAT Std', 'Bwd IAT Min', 'Flow IAT Min', 'Bwd Packet Length Std',
       'Bwd Packet Length Mean', 'Avg Bwd Segment Size', 'Idle Min',
       'Bwd Packet Length Max', 'Idle Mean', 'Packet Length Std', 'Idle Max',
       'Flow IAT Max', 'Max Packet Length', 'Fwd IAT Max',
       'Packet Length Variance', 'Average Packet Size', 'Packet Length Mean',
       'Active Min', 'FIN Flag Count', 'Active Std', 'Flow IAT Std',
       'PSH Flag Count', 'Active Mean', 'Fwd IAT Total', 'ACK Flag Count',
       'Flow Duration', 'Bwd IAT Std', 'Subflow Fwd Bytes', 'Flow IAT Mean',
       'Min Packet Length', 'Label'],
      dtype='object')

In [22]:
feature_list = pd.DataFrame(selected_features, columns=["Selected Features"])

feature_list.to_csv(
    PROJECT_DIR / "results" / "reports" / "selected_feature_names.csv",
    index=False
)

print(feature_list)

         Selected Features
0              Fwd IAT Std
1              Bwd IAT Min
2             Flow IAT Min
3    Bwd Packet Length Std
4   Bwd Packet Length Mean
5     Avg Bwd Segment Size
6                 Idle Min
7    Bwd Packet Length Max
8                Idle Mean
9        Packet Length Std
10                Idle Max
11            Flow IAT Max
12       Max Packet Length
13             Fwd IAT Max
14  Packet Length Variance
15     Average Packet Size
16      Packet Length Mean
17              Active Min
18          FIN Flag Count
19              Active Std
20            Flow IAT Std
21          PSH Flag Count
22             Active Mean
23           Fwd IAT Total
24          ACK Flag Count
25           Flow Duration
26             Bwd IAT Std
27       Subflow Fwd Bytes
28           Flow IAT Mean
29       Min Packet Length

# Summary

- Loaded cleaned CICIDS2017 dataset
- Separated features and labels
- Encoded attack labels
- Applied mRMR feature selection
- Selected the Top 30 most relevant features
- Saved the reduced dataset for further processing